### PR TITLE
UI fix and Reputation values

### PR DESCRIPTION
**Pull request by tvlfrosty**
Fixes the missing BackdropTemplate in classic, this fix was made for the retail version as well. Also changes some reputation values for Bloodsail buccaneers.

### CODE REVIEW

**Comment by tvlfrosty** [comment]
~~Sorry, making some more changes after testing some more rep values myself. Will re-open once I changed the values.~~ Apparently I can't edit the files while the PR is closed... And I didn't see the convert  to draft untill now. I appologies.

**Comment by tvlfrosty** [comment]
Obviously the non repeatable quest are not hidden once completed, perhaps this is something that could be added in the future, I am not the best with LUA coding just yet.

Perhaps there could be an option added to show non-repeatable quests or not, with a checkbox?

**Comment by chawan** [comment]
Thank you for all the fixes, everything looks fine to me so I will merge this and get it updated on Curse as well.

**Comment by chawan** [comment]
Looking a bit more we need to find another way to fix Darkmoon Faire cutting off some quests early. RPH_ToExalted is using the standingID that WoW provides which is a set number of 1-8. So unfortunately adding another entry to that will not work as it is not a valid standingID.

**Comment by tvlfrosty** [comment]
Hmm that's unfortunate... is it giving errors? or not working even if you are lower rep then it's suppose to be? because codewise you are just checking if you are higher or lower than the number you are setting at the quests no? so no matter what number you are getting back it would be either higher or lower than the 4.5?

Is there a way to check which standingID you get back if you are above or under the 2001/6000? or would it just return 4 or 5?

Hmm nvm it's not showing the "Yields reputation till" label.

**Comment by chawan** [comment]
It just checks your current standing with the faction and shows the entry if you are within the standings you set. 

0 - Unknown
1 - Hated
2 - Hostile
3 - Unfriendly
4 - Neutral
5 - Friendly
6 - Honored
7 - Revered
8 - Exalted

So setting from 4 to 6 for example would show the entry if you are neutral or higher but not higher than honored.

Checking the standing at 2001/6000 friendly should just return 5 for the standingID but it would return 5 all the way from 0/6000 friendly up until you hit honored.

Would probably need some specific checks just for the DMF quests that cutoff early or maybe add actual support for showing / hiding based on the actual reputation amount you have as well as the standing.

**Comment by tvlfrosty** [comment]
It feels like a really odd cut-off on their end.... Idk if it's just DMF quests that do it, but either way would require some work.
So depending on how much work it would be to make it check on current reputation as well as standing. (which I personally think would be the best solution). 

Perhaps this could be a future 'nice to have'? (the wowhead guide curerntly just shows 5999/6000 as well).

In the meantime if you want I can work on some of the tbc reputations/zones

**Comment by chawan** [comment]
Any help is appreciated.

**Pull request merged**
